language: cpp
dist: trusty
sudo: true

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
              - valgrind
              - libgoogle-glog-dev
              - g++-8
              - gcc-8
              - cmake
              - protobuf-compiler  libprotoc-dev
              - autoconf automake libtool


before_script:
  - export CC=gcc-8
  - export CXX=g++-8
  - export AR=gcc-ar-8
  - export RANLIB=gcc-ranlib-8
  - export NM=gcc-nm-8

# Build gtest
  - git clone https://github.com/google/googletest.git
  - cd googletest
  - cmake .
  - sudo cmake --build . --target install
  - cd -
# Build protobuf
  # - git clone https://github.com/protocolbuffers/protobuf.git
  # - cd protobuf
  # - ./autogen.sh && ./configure && make && sudo make install
  # - cd -

script:
   - make
   - make run-test
   - make check-style
